// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package container

import (
	"github.com/a3herrera/api-test/infrastructure/http"
	"github.com/a3herrera/api-test/infrastructure/http/rest"
	"github.com/a3herrera/api-test/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewServer() (http.Server, error) {
	healthHandler := rest.NewHealthHandler()
	searchService := service.NewSearchService()
	searchHandler := rest.NewSearchHandler(searchService)
	handlers := http.NewServerHandlers(healthHandler, searchHandler)
	server := http.New(handlers)
	return server, nil
}

// wire.go:

var servicesSet = wire.NewSet(service.NewSearchService)

var handlerSet = wire.NewSet(rest.NewHealthHandler, rest.NewSearchHandler, http.NewServerHandlers)
